### ISSUE TITLE
Call(cmdname string, format string, args ...interface{})

### ISSUE THREAD

**Issue by gudepeng** [wenerme/go-rm#9]
这个能不能给个例子呀，卡好几天了，方便给个联系方式吗？

**Comment by wenerme** [comment]
待会儿我看下给你回复

我是金角大王 <notifications@github.com>于2019年1月9日 周三上午10:32写道：

**Comment by wenerme** [comment]
@gudepeng 你是说的那个方法呢？看这个方法签名，因该是类似 `Call("hget","%s %s","key","field")` 这样的

**Comment by gudepeng** [comment]
好的，为试下。太谢谢你了。卡好几天了。

**Comment by gudepeng** [comment]
然后为这个按照官网的一个例子（c语言）：
RedisModuleCallReply *reply;

    reply = RedisModule_Call(ctx,"RPUSH","ss",argv[1],argv[2]);
    RedisModule_ReplyWithCallReply(ctx,reply);
    RedisModule_FreeCallReply(reply);
    return REDISMODULE_OK;

然后用你的go-rm
reply := ctx.Call("RPUSH", "%s %s %s", "ss", "gdpcs","111")
			ctx.ReplyWithCallReply(reply)
			reply.FreeCallReply()
			ctx.ReplyWithOK()
			return rm.OK
会报错：
段错误(吐核)

**Comment by gudepeng** [comment]
然后为在官网找了个例子（c语言）：
reply = RedisModule_Call(ctx,"RPUSH","ss",argv[1],argv[2]);
RedisModule_ReplyWithCallReply(ctx,reply);
RedisModule_FreeCallReply(reply);
return REDISMODULE_OK;
用你的go-rm调用：
reply := ctx.Call("RPUSH", "%s %s %s", "cc", "gdpcs","gdpcc1")
ctx.ReplyWithCallReply(reply)
reply.FreeCallReply()
ctx.ReplyWithOK()
报错：段错误(吐核)
那个参数尝试过很多种。
可以给个用call这种方式实际能运行起来的例子吗？

**Comment by wenerme** [comment]
我看了下，我的实现里调用 Call 有问题，你是打算实现什么样的功能呢

**Comment by gudepeng** [comment]
其实我有挺多逻辑要写在里面。其实就是想使用redis自带的这个call方法。方便给个联系方式吗？邮箱就行。

**Comment by gudepeng** [comment]
啊？你在哪联系的我，我邮箱：gudepeng@qq.com。哦哦。厉害厉害。我之前没写过c。其他也是有点不知道c里的这个多参数怎么传。go怎么调用多参c方法。我也试验了一些，但是都没好用。

**Comment by wenerme** [comment]
邮件联系你了，go 不支持调用 c 的变长参数方法，我是预先生成的，你看 callback.h

**Comment by gudepeng** [comment]
大神你使用微信或者qq吗？方便加个微信：gudepeng001 或者qq：706645538

**Comment by wenerme** [comment]
Call 的这个方法调用有点复杂，主要是 format 这个参数，以后有机会应该可以简化，省略这个参数。
下面的这个代码是实现了一个 mydel 命令，会直接调用 del 命令

```go
func CreateCommand_MYDEL() rm.Command {
	return rm.Command{
		Usage:    "MYDEL key",
		Desc:     "Call Del",
		Name:     "mydel",
		Flags:    "write fast deny-oom",
		FirstKey: 1, LastKey: 1, KeyStep: 1,
		Action: func(cmd rm.CmdContext) int {
			ctx, args := cmd.Ctx, cmd.Args
			if len(args) < 2 {
				return ctx.WrongArity()
			}
			ctx.AutoMemory()
			// 这里的 format s 表示传入的是一个 redis 的 string 对象，在 go-rm 里表示为 rm.String
			// 如果传错格式或参数，errno 会返回非 0
			replay := ctx.Call("DEL", "s", args[1])
			if ok, err := replay.IsErrno(); ok {
				ctx.ReplyWithError(fmt.Sprintf("Faield with %v", err))
				return rm.ERR
			}

			if replay.IsNull() {
				return rm.ERR
			}
			rm.LogDebug("Call mydel %V %v", args[1], args[1])

			return ctx.ReplyWithCallReply(replay)
		},
	}
}
```
